### ISSUE TITLE
[Error help] Build problems of micro ros and rtthread

### ISSUE THREAD

**Issue by kurisaW** [micro-ROS/micro_ros_rtthread_component#1]
@Acuadros95 Hello author, according to the README document of the warehouse, I have a Build problem in the step of 'Build the library'. Here is my warning message:

```c
Summary: 56 packages finished [1min 44s]
  2 packages had stderr output: gmock_vendor gtest_vendor
WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)
```

![image](https://github.com/micro-ROS/micro_ros_rtthread_component/assets/98592772/a6ce45eb-e9e3-49fa-8caa-9c047ce95479)

Here is my environment configuration:

```bash
- Python 3.8.10
- RT-Thread Env Tool v1.4.0
- cmake version 3.27.4
- pip 21.1.1 (python 3.8)
```

May I ask how I can solve this problem, and look forward to your relevant reply and answer

**Comment by kurisaW** [comment]
From what I've seen on the web, it seems like I can ignore this stderr problem, but I don't see the dependent packages downloaded successfully under 'micro_ros_rtthread_component\builder\extra_packages'

**Comment by pablogs9** [comment]
It seems that micro-ROS is being built correctly and there is something with scons, is that possible?

**Comment by kurisaW** [comment]
Although this looks like micro-ros has been successfully built, it stands to reason that you should be able to see the download of the relevant software packages under the path 'micro_ros_rtthread_component\builder\extra_packages'. In fact, this has not been achieved.
